### PR TITLE
created mkdir.js

### PR DESCRIPTION
**Pull request by Coretool**
I added a simple version of mkdir. Will add the arguments soon.

### CODE REVIEW

**Comment by piranna** [comment]
I'll wait until you add the arguments, but it's a good beginning :-(

**Comment by piranna** [comment]
:-)

(Sh*ty Android keyboard... :-P)

**Comment by Coretool** [comment]
Can I use "3rd" party modules ? Namely fs-extras and/or mkdir-p.

**Comment by piranna** [comment]
Of course you can if you think they make sense :-)

**Comment by Coretool** [comment]
Finished ! :-)

**Comment by piranna** [comment]
:+1:

**Pull request merged**
